create table franchises (
  franchise_id integer not null,
  franchise text not null
);

alter table franchises 
  alter column franchise_id 
    add generated by default as identity (
      sequence name franchise_id_seq
      start with 1
      increment by 1
      no minvalue
      no maxvalue
      cache 1
    );

alter table franchises
  add constraint franchises_pkey 
  primary key (franchise_id);

create table societes (
  societe_id uuid default gen_random_uuid() not null primary key,
  societe text not null,
  uei text
);

create table certifications (
  certification_id integer not null,
  pays text,
  ordre smallint,
  certification text,
  description text
);

alter table certifications 
  alter column certification_id 
    add generated by default as identity (
      sequence name certification_id_seq
      start with 1
      increment by 1
      no minvalue
      no maxvalue
      cache 1
    );

alter table certifications
  add constraint certifications_pkey 
  primary key (certification_id);
