create table salles (
  salle_id integer not null,
  etablissement_id integer not null,
  salle text not null,
  sieges integer not null
);

alter table salles
  add constraint salle_etablissement_fk foreign key (etablissement_id)
        references etablissements (etablissement_id) match simple
        on update no action
        on delete no action
        not valid;

create index on salles 
  using btree (etablissement_id);

alter table salles 
  alter column salle_id 
    add generated by default as identity (
      sequence name salle_id_seq
      start with 1
      increment by 1
      no minvalue
      no maxvalue
      cache 1
    );

alter table salles
  add constraint salle_pkey 
  primary key (salle_id);


create table seances (
 seance_id integer not null,
  film_id uuid not null,
  salle_id integer not null,
  seance date not null
);

alter table seances 
  alter column seance_id 
    add generated by default as identity (
      sequence name seance_id_seq
      start with 1
      increment by 1
      no minvalue
      no maxvalue
      cache 1
    );

alter table seances
  add constraint seances_pkey 
  primary key (seance_id);

create index on seances 
  using btree (film_id);

create index on seances 
  using btree (salle_id);

alter table seances
  add constraint seance_salle_fk foreign key (salle_id)
    references salles (salle_id) match simple
    on update no action
    on delete no action
    not valid;

alter table seances
  add constraint seance_film_fk foreign key (film_id)
    references films (film_id) match simple
    on update no action
    on delete no action
    not valid;
