create table familles (
  famille_id integer,
  famille_parent integer,
  famille text
);

alter table familles
  add constraint familles_pkey 
  primary key (famille_id);

alter table familles 
  alter column famille_id 
    add generated by default as identity (
      sequence name famille_id_seq
      start with 1
      increment by 1
      no minvalue
      no maxvalue
      cache 1
    );
